### PR TITLE
aeiou2

### PR DESCRIPTION
**Pull request by rzats**

### CODE REVIEW

**Comment by rzats** [comment]
test

**Comment by rzats** [comment]
test3

**Comment by rzats** [comment]
test4

**Comment by rzats** [comment]
test without ping

**Comment by rzats** [comment]
@BenFradet test with ping

**Comment by BenFradet** [comment]
Please sign the CLA: https://github.com/snowplow/snowplow/wiki/CLA.
Once you signed it, ping the bot.

**Comment by rzats** [comment]
@BenFradet

**Comment by rzats** [comment]
@BenFradet I signed it

**Comment by BenFradet** [comment]
Thanks for signing the CLA!

**Pull request closed without merging**
